spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toeic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      properties:
      format_sql: true
    open-in-view: true

profiles:
    active: dev

#logging:
#  level:
#    org.hibernate.SQL: debug