spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toeic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghlim909@gmail.com
    password: geonho1234!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 602673167587-j93qmaktsgv3niij5uoh9ogtm5g47fl2.apps.googleusercontent.com
            client-secret: aWWmk52hbXL4wGsDBPsjrLpc
            scope:
              - email
              - profile

  profiles:
    active: dev

#logging:
#  level:
#    org.hibernate.SQL: debug


