spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toeic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      ddl-auto: none
    properties:
      format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghlim909@gmail.com
    password: geonho1234!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: dev

#logging:
#  level:
#    org.hibernate.SQL: debug


