spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/toeic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghlim909@gmail.com
    password: geonho0401!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 602673167587-j93qmaktsgv3niij5uoh9ogtm5g47fl2.apps.googleusercontent.com
            client-secret: aWWmk52hbXL4wGsDBPsjrLpc
            scope:
              - email
              - profile
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    active: service

#logging:
#  level:
#    org.hibernate.SQL: debug


